name: chat_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  core:
    path: 'core'

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  auto_route: ^7.8.0
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  google_sign_in_mocks: ^0.3.0
  firebase_auth_mocks: ^0.12.0
  mockito: ^5.4.2
  flutter_bloc: ^8.1.3
  injectable: ^2.2.0
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  injectable_generator: ^2.3.0

flutter:
  uses-material-design: true
