name: chat_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+31

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  auto_route: ^7.8.0
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  mockito: ^5.4.2
  flutter_bloc: ^8.1.3
  injectable: ^2.2.0

  core:
    path: "packages/core"
  get_it: ^7.6.0
  equatable: ^2.0.5
  flutter_screenutil: ^5.8.4
  coolicons: ^1.0.0
  flutter_hooks: ^0.20.1
  kt_dart: ^1.1.0
  rxdart: ^0.27.7
  uuid: ^3.0.7
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.2.3
  scroll_to_index: ^3.0.1
  bloc: ^8.1.2
  collection: ^1.17.1
  path: ^1.8.3
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.3.3
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  injectable_generator: ^2.3.0
  melos: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter: 
  uses-material-design: true
  assets:
    - packages/core/assets/images/
    - packages/core/assets/icons/
  
