name: core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_route: ^7.8.0
  bloc: ^8.1.2
  cloud_firestore: ^4.9.2
  dartz: ^0.10.1
  fake_cloud_firestore: ^2.4.1+1
  firebase_auth: ^4.10.0
  firebase_auth_mocks: ^0.12.0
  firebase_storage: ^11.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_image_compress: ^2.0.4
  flutter_screenutil: ^5.8.4
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  google_sign_in_mocks: ^0.3.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  injectable: ^2.2.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  kt_dart: ^1.1.0
  mockito: ^5.4.2
  path: any
  path_provider: ^2.1.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  injectable_generator: ^2.3.0
  auto_route_generator: ^7.3.0


flutter: